spring.application.name=Rag-storyBook
spring.application.name=Rag_storyBook

qdrant.url=https://ed07f1e1-6917-4823-8313-008858e97fb8.eu-central-1-0.aws.cloud.qdrant.io
qdrant.api-key=${QDRANT_API_KEY}
qdrant.collection=story_book